#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env
VCS_REF=${GIT_SHA1}
BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
BUILD_TYPE=${BUILD_TYPE}
BEANSTALKD_VERSION=${BEANSTALKD_VERSION}

EOF

docker-compose \
  --file compose/head.yml \
  --file compose/beanstalkd.yml \
  config > docker-compose.yml
